# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbomPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=32, verbose_name='название фото')),
                ('photo_pol', models.PositiveIntegerField(verbose_name='голоса за фото')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlboms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albom_name', models.CharField(max_length=32, verbose_name='название альбома')),
                ('albom_catefory', models.CharField(max_length=32, verbose_name='категория альбома')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='связка с ID из users')),
                ('type_profile', models.CharField(max_length=32, verbose_name='тип профиля')),
                ('link', models.URLField(max_length=90, verbose_name='ссылка на личный сайт')),
                ('about_me', models.TextField(verbose_name='коротко о себе')),
                ('avatar', models.CharField(max_length=32, verbose_name='путь до картинки')),
            ],
        ),
        migrations.AddField(
            model_name='useralboms',
            name='id_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorlOfPhotos.UserProfile', verbose_name='связка с ID из users_profile'),
        ),
        migrations.AddField(
            model_name='albomphotos',
            name='id_albom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorlOfPhotos.UserProfile', verbose_name='связка с ID из UsersAlbom'),
        ),
    ]
